export const LEVELS = [
  {
    id: 'first-light',
    title: 'First Light',
    hint: 'Stand on A and rewind. Your echo will return to A and hold gate a open.',
    grid: [
      '#########',
      '#S..a..X#',
      '#.###.###',
      '#A###o###',
      '#########',
      '#########',
    ],
  },
  {
    id: 'afterimage',
    title: 'Afterimage',
    hint: 'Park an echo on A. Collect both crystals in your final run, then find the northern gate.',
    grid: [
      '##########',
      '#S.o#a..X#',
      '#.#.#.####',
      '#.#...o###',
      '#A###.####',
      '#.....####',
      '##########',
    ],
  },
  {
    id: 'double-exposure',
    title: 'Double Exposure',
    hint: 'Record A first. Use that echo to reach B, record again, then collect the crystal before leaving.',
    grid: [
      '##########',
      '#S..a..bX#',
      '#.###.####',
      '#A###.####',
      '#####B####',
      '#####o####',
      '##########',
    ],
  },
  {
    id: 'crossed-paths',
    title: 'Crossed Paths',
    hint: 'Leave echoes on A and B. Rewinding restores the crystals, so visit the lower-left crystal again on your final run.',
    grid: [
      '##########',
      '#S..a...##',
      '#.#.###.##',
      '#A#...#o##',
      '#.###.#.##',
      '#o..B.#bX#',
      '#.....#..#',
      '##########',
    ],
  },
  {
    id: 'event-horizon',
    title: 'Event Horizon',
    hint: 'Record A, then reach B through gate a and record B. On the final run, explore all three crystal branches before the eastern exit.',
    grid: [
      '##########',
      '#S..a....#',
      '#.###.##.#',
      '#A#o..##o#',
      '#.###.##.#',
      '#..o#B##b#',
      '########X#',
      '##########',
    ],
  },
];
